import type { Metadata } from "next";
import { Story_Script, Inter, Geist_Mono  } from "next/font/google";
import "./globals.css";
import NavBar from "./components/navbar";

const storyScript = Story_Script({
  variable: "--font-heading",
  subsets: ["latin"],
  weight: "400"
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const interFont = Inter({
  variable: "--font-body",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${storyScript.variable} ${interFont.variable} h-full antialiased`}
    >

      <body className="min-h-full flex flex-col">
        <NavBar/>
        {children}

      </body>
      
    </html>
  );
}
